-- ============================================================
--  Spark Code CLI — Authentication Schema
--  Paste this in Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS spark_cli_sessions (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    device_code  TEXT        UNIQUE NOT NULL,          -- random UUID generated by CLI
    pin          TEXT,                                  -- 6-digit code shown in browser
    user_id      UUID        REFERENCES auth.users(id) ON DELETE CASCADE,
    user_email   TEXT,
    status       TEXT        NOT NULL DEFAULT 'pending'
                             CHECK (status IN ('pending', 'pin_ready', 'verified', 'expired')),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    expires_at   TIMESTAMPTZ DEFAULT NOW() + INTERVAL '10 minutes'
);

CREATE INDEX IF NOT EXISTS idx_cli_sessions_device_code ON spark_cli_sessions(device_code);
CREATE INDEX IF NOT EXISTS idx_cli_sessions_expires_at  ON spark_cli_sessions(expires_at);

-- No RLS — accessed by service role from both CLI and web
ALTER TABLE spark_cli_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_cli_sessions"
    ON spark_cli_sessions FOR ALL
    USING (auth.role() = 'service_role');

-- Auto-expire old sessions (run as a cron or manually)
-- DELETE FROM spark_cli_sessions WHERE expires_at < NOW();
